@startuml 1.baseapp的类图
    title 1.baseapp的类图

    namespace Tendermint #SkyBlue {
        namespace abci.types {
            interface Application {
                =<color:DarkGreen>ABCI 查询接口
                ----
                Info(RequestInfo) ResponseInfo
                ....
                Query(RequestQuery) ResponseQuery
                ====
                =<color:DarkGreen>ABCI Mempool接口
                ----
                CheckTx(RequestCheckTx) ResponseCheckTx
                ====
                =<color:DarkGreen>ABCI 共识接口
                ----
                BeginBlock(RequestBeginBlock) ResponseBeginBlock
                ....
                DeliverTx(RequestDeliverTx) ResponseDeliverTx
                ....
                EndBlock(RequestEndBlock) ResponseEndBlock
                ....
                Commit() ResponseCommit
                ====
                =<color:DarkGreen>ABCI snapshot接口
                ----
                ListSnapshots(RequestListSnapshots) ResponseListSnapshots
                ....
                OfferSnapshot(RequestOfferSnapshot) ResponseOfferSnapshot
                ....
                LoadSnapshotChunk(RequestLoadSnapshotChunk) ResponseLoadSnapshotChunk
                ....
                ApplySnapshotChunk(RequestApplySnapshotChunk) ResponseApplySnapshotChunk
            }
        }
    }

    namespace CosmosSDK {
        namespace baseapp {
            struct BaseApp {
                txDecoder // tx 解码函数指针
                ....
                appStore
                ....
                moduleRouter
            }

            Tendermint.abci.types.Application <|-- BaseApp
        }
    }

    namespace Ethermint {
        namespace app {
            struct EthermintApp {
                //<color:DarkGreen> substore 的 keys
                ----
                //<b><color:DarkGreen> 所有功能模块的 Keeper 对象
                ----
                mm *module.Manager
            }

            CosmosSDK.baseapp.BaseApp <|-- EthermintApp : 嵌入BaseApp实现继承
        }
    }

@enduml